/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.33
 * Generated at: 2025-01-08 00:45:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.site;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/04_Middle/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hurdles/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664421078000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1735043174827L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fproperty_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fproperty_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_c_005fset_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("	<meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("	\n");
      out.write("	<title>허들 - 마슈</title>\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/site/layout/prestyle.jsp", out, false);
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"index-page\">\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/site/layout/header.jsp", out, false);
      out.write("\n");
      out.write("  <main>\n");
      out.write("\n");
      out.write("    <!-- Hero Section -->\n");
      out.write("    <section id=\"hero\" class=\"hero section light-background\">\n");
      out.write("\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"row gy-4 justify-content-center justify-content-lg-between\">\n");
      out.write("          <div class=\"col-lg-5 order-2 order-lg-1 d-flex flex-column justify-content-center\">\n");
      out.write("            <h1 data-aos=\"fade-up\">맛있는 선택,<br>행복한 하루<br>Mashu<span class=\"red-boll\">.</span></h1>\n");
      out.write("            <p data-aos=\"fade-up\" data-aos-delay=\"100\">당신의 한 끼를 특별하게, Mashu<span class=\"red-boll\">.</span>가 책임집니다!</p>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-lg-5 order-1 order-lg-2 hero-img\" data-aos=\"zoom-out\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/hero-img.png\" class=\"img-fluid animated\" alt=\"\">\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("    </section><!-- /Hero Section -->\n");
      out.write("\n");
      out.write("    <!-- About Section -->\n");
      out.write("    <section id=\"about\" class=\"about section\">\n");
      out.write("\n");
      out.write("      <!-- Section Title -->\n");
      out.write("      <div class=\"container section-title\" data-aos=\"fade-up\">\n");
      out.write("        <h2>About Us<br></h2>\n");
      out.write("        <p><span>Learn More</span> <span class=\"description-title\">About Us</span></p>\n");
      out.write("      </div><!-- End Section Title -->\n");
      out.write("\n");
      out.write("      <div class=\"container\">\n");
      out.write("\n");
      out.write("        <div class=\"row gy-4\">\n");
      out.write("          <div class=\"col-lg-7\" data-aos=\"fade-up\" data-aos-delay=\"100\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/about.jpg\" class=\"img-fluid mb-4\" alt=\"\">\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-lg-5\" data-aos=\"fade-up\" data-aos-delay=\"250\">\n");
      out.write("            <div class=\"content ps-0 ps-lg-5\">\n");
      out.write("              <p class=\"fst-italic\">\n");
      out.write("                  우리는 고객님과 지역 맛집을 연결하는 최고의 음식 플랫폼입니다.  \n");
      out.write("                  신선한 재료와 다양한 메뉴를 통해 더욱 특별한 식사 경험을 제공합니다.\n");
      out.write("              </p>\n");
      out.write("              <ul>\n");
      out.write("                <li><i class=\"bi bi-check-circle-fill\"></i> <span>수백 개의 다양한 레스토랑 메뉴를 한곳에서 비교하고 선택하세요.</span></li>\n");
      out.write("                <li><i class=\"bi bi-check-circle-fill\"></i> <span>빠르고 신뢰할 수 있는 배달 서비스로 따뜻한 음식을 받아보세요.</span></li>\n");
      out.write("                <li><i class=\"bi bi-check-circle-fill\"></i> <span>정기적인 할인과 혜택으로 더 알뜰하게 즐기세요.</span></li>\n");
      out.write("              </ul>\n");
      out.write("              <p>\n");
      out.write("                우리의 목표는 단순한 식사 이상의 가치를 제공하는 것입니다.  \n");
      out.write("                오늘도 최고의 음식을 쉽고 편리하게 즐길 수 있도록 최선을 다하겠습니다!\n");
      out.write("              </p>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("    </section><!-- /About Section -->\n");
      out.write("\n");
      out.write("    <!-- Why Us Section -->\n");
      out.write("    <section id=\"why-us\" class=\"why-us section light-background\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"row gy-4\">\n");
      out.write("          <div class=\"col-lg-4\" data-aos=\"fade-up\" data-aos-delay=\"100\">\n");
      out.write("            <div class=\"why-box\">\n");
      out.write("              <h3>Mashu<span class=\"red-boll\">.</span></h3>\n");
      out.write("              <br>\n");
      out.write("              <p>\n");
      out.write("                마슈는 지역의 인기 맛집부터 숨겨진 보석 같은 <br>레스토랑까지 수많은 음식점을 한곳에서 만날 수 있는 플랫폼입니다. <br>\n");
      out.write("                간단한 검색만으로 다양한 음식 카테고리를 <br>탐색하고,한식, 양식, 중식, 디저트 등 원하는 메뉴를 손쉽게 선택할 수 있습니다. <br>\n");
      out.write("                새로운 맛집을 발견하거나 좋아하는 단골 음식점을 간편하게 주문할 수 있어,<br>고객의 미식 경험을 더욱 풍부하게 만들어 드립니다.\n");
      out.write("              </p>\n");
      out.write("            </div>\n");
      out.write("          </div><!-- End Why Box -->\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-8 d-flex align-items-stretch\">\n");
      out.write("            <div class=\"row gy-4\" data-aos=\"fade-up\" data-aos-delay=\"200\">\n");
      out.write("\n");
      out.write("              <div class=\"col-xl-4\">\n");
      out.write("                <div class=\"icon-box d-flex flex-column justify-content-center align-items-center\">\n");
      out.write("                  <i class=\"bi bi-clipboard-data\"></i>\n");
      out.write("                  <h4>다양한 선택과 편리함</h4>\n");
      out.write("                  <p>우리의 플랫폼은 다양한 음식점과 메뉴를 한곳에서 확인할 수 있는 최고의 편리함을 제공합니다. 고객의 기호와 현재 위치에 따라 맞춤형 추천을 제공하여 선택을 더욱 간단하게 만듭니다.</p>\n");
      out.write("                </div>\n");
      out.write("              </div><!-- End Icon Box -->\n");
      out.write("\n");
      out.write("              <div class=\"col-xl-4\" data-aos=\"fade-up\" data-aos-delay=\"300\">\n");
      out.write("                <div class=\"icon-box d-flex flex-column justify-content-center align-items-center\">\n");
      out.write("                  <i class=\"bi bi-gem\"></i>\n");
      out.write("                  <h4>빠르고 신뢰할 수 있는 서비스</h4>\n");
      out.write("                  <p>주문부터 배달까지 빠르고 정확한 프로세스를 통해 고객의 시간을 절약합니다. 신뢰할 수 있는 배달 파트너와 함께하여 항상 신선하고 뜨거운 음식을 제공합니다.</p>\n");
      out.write("                </div>\n");
      out.write("              </div><!-- End Icon Box -->\n");
      out.write("\n");
      out.write("              <div class=\"col-xl-4\" data-aos=\"fade-up\" data-aos-delay=\"400\">\n");
      out.write("                <div class=\"icon-box d-flex flex-column justify-content-center align-items-center\">\n");
      out.write("                  <i class=\"bi bi-inboxes\"></i>\n");
      out.write("                  <h4>합리적인 가격과 특별 혜택</h4>\n");
      out.write("                  <p>정기적인 할인, 프로모션, 포인트 적립 등 다양한 혜택을 통해 고객에게 최고의 가성비를 제공합니다. 우리 플랫폼을 이용할수록 더 큰 혜택을 누릴 수 있습니다.</p>\n");
      out.write("                </div>\n");
      out.write("              </div><!-- End Icon Box -->\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("    </section><!-- /Why Us Section -->\n");
      out.write("\n");
      out.write("    <!-- Stats Section -->\n");
      out.write("    <section id=\"stats\" class=\"stats section dark-background\">\n");
      out.write("\n");
      out.write("      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/stats-bg.jpg\" alt=\"\" data-aos=\"fade-in\">\n");
      out.write("\n");
      out.write("      <div class=\"container position-relative\" data-aos=\"fade-up\" data-aos-delay=\"100\">\n");
      out.write("\n");
      out.write("        <div class=\"row gy-4\">\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-3 col-md-6\">\n");
      out.write("            <div class=\"stats-item text-center w-100 h-100\">\n");
      out.write("              <span data-purecounter-start=\"0\" data-purecounter-end=\"232\" data-purecounter-duration=\"1\" class=\"purecounter\"></span>\n");
      out.write("              <p>사용자</p>\n");
      out.write("            </div>\n");
      out.write("          </div><!-- End Stats Item -->\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-3 col-md-6\">\n");
      out.write("            <div class=\"stats-item text-center w-100 h-100\">\n");
      out.write("              <span data-purecounter-start=\"0\" data-purecounter-end=\"521\" data-purecounter-duration=\"1\" class=\"purecounter\"></span>\n");
      out.write("              <p>가맹 점포수</p>\n");
      out.write("            </div>\n");
      out.write("          </div><!-- End Stats Item -->\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-3 col-md-6\">\n");
      out.write("            <div class=\"stats-item text-center w-100 h-100\">\n");
      out.write("              <span data-purecounter-start=\"0\" data-purecounter-end=\"1453\" data-purecounter-duration=\"1\" class=\"purecounter\"></span>\n");
      out.write("              <p>플랫폼 결제 건수</p>\n");
      out.write("            </div>\n");
      out.write("          </div><!-- End Stats Item -->\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-3 col-md-6\">\n");
      out.write("            <div class=\"stats-item text-center w-100 h-100\">\n");
      out.write("              <span data-purecounter-start=\"0\" data-purecounter-end=\"32\" data-purecounter-duration=\"1\" class=\"purecounter\"></span>\n");
      out.write("              <p>일일 마슈 이용고객 수</p>\n");
      out.write("            </div>\n");
      out.write("          </div><!-- End Stats Item -->\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("    </section><!-- /Stats Section -->\n");
      out.write("\n");
      out.write("    <!-- Testimonials Section -->\n");
      out.write("    <section id=\"testimonials\" class=\"testimonials section light-background\">\n");
      out.write("\n");
      out.write("      <!-- Section Title -->\n");
      out.write("      <div class=\"container section-title\" data-aos=\"fade-up\">\n");
      out.write("        <h2>TESTIMONIALS</h2>\n");
      out.write("        <p>What Are They <span class=\"description-title\">Saying About Us</span></p>\n");
      out.write("      </div><!-- End Section Title -->\n");
      out.write("\n");
      out.write("      <div class=\"container\" data-aos=\"fade-up\" data-aos-delay=\"100\">\n");
      out.write("\n");
      out.write("        <div class=\"swiper init-swiper\">\n");
      out.write("          <script type=\"application/json\" class=\"swiper-config\">\n");
      out.write("            {\n");
      out.write("              \"loop\": true,\n");
      out.write("              \"speed\": 600,\n");
      out.write("              \"autoplay\": {\n");
      out.write("                \"delay\": 5000\n");
      out.write("              },\n");
      out.write("              \"slidesPerView\": \"auto\",\n");
      out.write("              \"pagination\": {\n");
      out.write("                \"el\": \".swiper-pagination\",\n");
      out.write("                \"type\": \"bullets\",\n");
      out.write("                \"clickable\": true\n");
      out.write("              }\n");
      out.write("            }\n");
      out.write("          </script>\n");
      out.write("          <div class=\"swiper-wrapper\">\n");
      out.write("            <div class=\"swiper-slide\">\n");
      out.write("              <div class=\"testimonial-item\">\n");
      out.write("                <div class=\"row gy-4 justify-content-center\">\n");
      out.write("                  <div class=\"col-lg-6\">\n");
      out.write("                    <div class=\"testimonial-content\">\n");
      out.write("                      <p>\n");
      out.write("                        <i class=\"bi bi-quote quote-icon-left\"></i>\n");
      out.write("                        <span>처음 이용해봤는데 정말 만족스러웠습니다. 음식도 따뜻하게 도착했고, 배달도 너무 빨랐어요. 앞으로도 자주 이용할 것 같아요!</span>\n");
      out.write("                        <i class=\"bi bi-quote quote-icon-right\"></i>\n");
      out.write("                      </p>\n");
      out.write("                      <h3>김지현</h3>\n");
      out.write("                      <h4>직장인</h4>\n");
      out.write("                      <div class=\"stars\">\n");
      out.write("                        <i class=\"bi bi-star-fill\"></i><i class=\"bi bi-star-fill\"></i><i class=\"bi bi-star-fill\"></i><i class=\"bi bi-star-fill\"></i><i class=\"bi bi-star-fill\"></i>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"col-lg-2 text-center\">\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/undraw_profile.svg\" class=\"img-fluid testimonial-img\" alt=\"Testimonial Image\">\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div><!-- End testimonial item -->\n");
      out.write("\n");
      out.write("            <div class=\"swiper-slide\">\n");
      out.write("              <div class=\"testimonial-item\">\n");
      out.write("                <div class=\"row gy-4 justify-content-center\">\n");
      out.write("                  <div class=\"col-lg-6\">\n");
      out.write("                    <div class=\"testimonial-content\">\n");
      out.write("                      <p>\n");
      out.write("                        <i class=\"bi bi-quote quote-icon-left\"></i>\n");
      out.write("                        <span>다양한 메뉴와 합리적인 가격이 정말 좋았어요. 무엇보다 정기적인 프로모션 덕분에 더 저렴하게 맛있는 음식을 즐길 수 있어서 만족합니다.</span>\n");
      out.write("                        <i class=\"bi bi-quote quote-icon-right\"></i>\n");
      out.write("                      </p>\n");
      out.write("                      <h3>이민수</h3>\n");
      out.write("                      <h4>대학생</h4>\n");
      out.write("                      <div class=\"stars\">\n");
      out.write("                        <i class=\"bi bi-star-fill\"></i><i class=\"bi bi-star-fill\"></i><i class=\"bi bi-star-fill\"></i><i class=\"bi bi-star-fill\"></i><i class=\"bi bi-star-fill\"></i>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"col-lg-2 text-center\">\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/undraw_profile.svg\" class=\"img-fluid testimonial-img\" alt=\"Testimonial Image\">\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div><!-- End testimonial item -->\n");
      out.write("\n");
      out.write("            <div class=\"swiper-slide\">\n");
      out.write("              <div class=\"testimonial-item\">\n");
      out.write("                <div class=\"row gy-4 justify-content-center\">\n");
      out.write("                  <div class=\"col-lg-6\">\n");
      out.write("                    <div class=\"testimonial-content\">\n");
      out.write("                      <p>\n");
      out.write("                        <i class=\"bi bi-quote quote-icon-left\"></i>\n");
      out.write("                        <span>친절한 고객 서비스에 정말 감동받았습니다. 배달 오류가 있었지만 빠르게 대응해 주셔서 기분 좋게 이용할 수 있었습니다. 믿고 사용하는 플랫폼이에요!</span>\n");
      out.write("                        <i class=\"bi bi-quote quote-icon-right\"></i>\n");
      out.write("                      </p>\n");
      out.write("                      <h3>박수현</h3>\n");
      out.write("                      <h4>프리랜서</h4>\n");
      out.write("                      <div class=\"stars\">\n");
      out.write("                        <i class=\"bi bi-star-fill\"></i><i class=\"bi bi-star-fill\"></i><i class=\"bi bi-star-fill\"></i><i class=\"bi bi-star-fill\"></i><i class=\"bi bi-star-fill\"></i>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"col-lg-2 text-center\">\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/undraw_profile.svg\" class=\"img-fluid testimonial-img\" alt=\"Testimonial Image\">\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div><!-- End testimonial item -->\n");
      out.write("\n");
      out.write("            <div class=\"swiper-slide\">\n");
      out.write("              <div class=\"testimonial-item\">\n");
      out.write("                <div class=\"row gy-4 justify-content-center\">\n");
      out.write("                  <div class=\"col-lg-6\">\n");
      out.write("                    <div class=\"testimonial-content\">\n");
      out.write("                      <p>\n");
      out.write("                        <i class=\"bi bi-quote quote-icon-left\"></i>\n");
      out.write("                        <span>추천 시스템이 정말 좋아요! 제가 좋아할 만한 메뉴를 추천해줘서 고민할 필요 없이 맛있는 음식을 바로 선택할 수 있었어요.</span>\n");
      out.write("                        <i class=\"bi bi-quote quote-icon-right\"></i>\n");
      out.write("                      </p>\n");
      out.write("                      <h3>최영훈</h3>\n");
      out.write("                      <h4>IT 개발자</h4>\n");
      out.write("                      <div class=\"stars\">\n");
      out.write("                        <i class=\"bi bi-star-fill\"></i><i class=\"bi bi-star-fill\"></i><i class=\"bi bi-star-fill\"></i><i class=\"bi bi-star-fill\"></i><i class=\"bi bi-star-fill\"></i>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"col-lg-2 text-center\">\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/undraw_profile.svg\" class=\"img-fluid testimonial-img\" alt=\"Testimonial Image\">\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div><!-- End testimonial item -->\n");
      out.write("\n");
      out.write("            <div class=\"swiper-slide\">\n");
      out.write("              <div class=\"testimonial-item\">\n");
      out.write("                <div class=\"row gy-4 justify-content-center\">\n");
      out.write("                  <div class=\"col-lg-6\">\n");
      out.write("                    <div class=\"testimonial-content\">\n");
      out.write("                      <p>\n");
      out.write("                        <i class=\"bi bi-quote quote-icon-left\"></i>\n");
      out.write("                        <span>다른 플랫폼보다 배달 속도가 빠르고 음식 상태도 훌륭했어요. 믿을 수 있는 서비스 덕분에 가족들과 함께하는 시간이 더 즐거워졌습니다.</span>\n");
      out.write("                        <i class=\"bi bi-quote quote-icon-right\"></i>\n");
      out.write("                      </p>\n");
      out.write("                      <h3>정은지</h3>\n");
      out.write("                      <h4>주부</h4>\n");
      out.write("                      <div class=\"stars\">\n");
      out.write("                        <i class=\"bi bi-star-fill\"></i><i class=\"bi bi-star-fill\"></i><i class=\"bi bi-star-fill\"></i><i class=\"bi bi-star-fill\"></i><i class=\"bi bi-star-fill\"></i>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"col-lg-2 text-center\">\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/undraw_profile.svg\" class=\"img-fluid testimonial-img\" alt=\"Testimonial Image\">\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div><!-- End testimonial item -->\n");
      out.write("\n");
      out.write("          </div>\n");
      out.write("          <div class=\"swiper-pagination\"></div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("    </section><!-- /Testimonials Section -->\n");
      out.write("  </main>\n");
      out.write("	\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/site/layout/footer.jsp", out, false);
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/site/layout/prescript.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/view/site/main.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("nav");
    // /WEB-INF/view/site/main.jsp(5,0) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/site/main.jsp(5,0) 'main'",_jsp_getExpressionFactory().createValueExpression("main",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/view/site/main.jsp(5,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setScope("request");
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f1.setParent(null);
    // /WEB-INF/view/site/main.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setVar("titleName");
    // /WEB-INF/view/site/main.jsp(6,0) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/site/main.jsp(6,0) '메인'",_jsp_getExpressionFactory().createValueExpression("메인",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/view/site/main.jsp(6,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setScope("request");
    int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
    if (_jspx_th_c_005fset_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f2.setParent(null);
    // /WEB-INF/view/site/main.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f2.setVar("paging");
    // /WEB-INF/view/site/main.jsp(7,0) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/site/main.jsp(7,0) '${paginationInfo}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${paginationInfo}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
    if (_jspx_th_c_005fset_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f3(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fproperty_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f3.setParent(null);
    // /WEB-INF/view/site/main.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f3.setVar("pagingOption");
    // /WEB-INF/view/site/main.jsp(8,0) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f3.setProperty("");
    // /WEB-INF/view/site/main.jsp(8,0) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f3.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/site/main.jsp(8,0) '${paginationInfo.getSearchVo()}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${paginationInfo.getSearchVo()}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
    if (_jspx_th_c_005fset_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fproperty_005fnobody.reuse(_jspx_th_c_005fset_005f3);
    return false;
  }
}
