/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.33
 * Generated at: 2025-01-07 05:47:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/04_Middle/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hurdles/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fmt-1_1.tld", Long.valueOf(1664421078000L));
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/04_Middle/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hurdles/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664421078000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1735043174827L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("   <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("   \n");
      out.write("   <title>관리자 메인</title>\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/admin/layout/prestyle.jsp", out, false);
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("     <!-- Sidebar -->\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/admin/layout/header.jsp", out, false);
      out.write("\n");
      out.write("     <!-- End of Sidebar -->\n");
      out.write("\n");
      out.write("     <!-- Begin Page Content -->\n");
      out.write("     <div class=\"container-fluid\">\n");
      out.write("\n");
      out.write("         <!-- Content Row -->\n");
      out.write("         <div class=\"row\">\n");
      out.write("\n");
      out.write("             <!-- Earnings (Monthly) Card Example -->\n");
      out.write("             <div class=\"col-xl-3 col-md-6 mb-4\">\n");
      out.write("                 <div class=\"card border-left-primary shadow h-100 py-2\">\n");
      out.write("                     <div class=\"card-body\">\n");
      out.write("                         <div class=\"row no-gutters align-items-center\">\n");
      out.write("                             <div class=\"col mr-2\">\n");
      out.write("                                 <div class=\"text-xs font-weight-bold text-primary text-uppercase mb-1\">\n");
      out.write("                                     예약 수</div>\n");
      out.write("                                 <div class=\"h5 mb-0 font-weight-bold text-gray-800\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reservationCnt }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("                             </div>\n");
      out.write("                             <div class=\"col-auto\">\n");
      out.write("                                 <i class=\"fas fa-calendar fa-2x text-gray-300\"></i>\n");
      out.write("                             </div>\n");
      out.write("                         </div>\n");
      out.write("                     </div>\n");
      out.write("                 </div>\n");
      out.write("             </div>\n");
      out.write("\n");
      out.write("             <!-- Earnings (Monthly) Card Example -->\n");
      out.write("             <div class=\"col-xl-3 col-md-6 mb-4\">\n");
      out.write("                 <div class=\"card border-left-success shadow h-100 py-2\">\n");
      out.write("                     <div class=\"card-body\">\n");
      out.write("                         <div class=\"row no-gutters align-items-center\">\n");
      out.write("                             <div class=\"col mr-2\">\n");
      out.write("                                 <div class=\"text-xs font-weight-bold text-success text-uppercase mb-1\">\n");
      out.write("                                     총 매출</div>\n");
      out.write("                                 <div class=\"h5 mb-0 font-weight-bold text-gray-800\">₩ ");
      if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_page_context))
        return;
      out.write("원</div>\n");
      out.write("                             </div>\n");
      out.write("                             <div class=\"col-auto\">\n");
      out.write("                                 <i class=\"fas fa-dollar-sign fa-2x text-gray-300\"></i>\n");
      out.write("                             </div>\n");
      out.write("                         </div>\n");
      out.write("                     </div>\n");
      out.write("                 </div>\n");
      out.write("             </div>\n");
      out.write("\n");
      out.write("             <!-- Earnings (Monthly) Card Example -->\n");
      out.write("             <div class=\"col-xl-3 col-md-6 mb-4\">\n");
      out.write("                 <div class=\"card border-left-info shadow h-100 py-2\">\n");
      out.write("                     <div class=\"card-body\">\n");
      out.write("                         <div class=\"row no-gutters align-items-center\">\n");
      out.write("                             <div class=\"col mr-2\">\n");
      out.write("                                 <div class=\"text-xs font-weight-bold text-info text-uppercase mb-1\">주문건 당 리뷰작성률\n");
      out.write("                                 </div>\n");
      out.write("                                 <div class=\"row no-gutters align-items-center\">\n");
      out.write("                                     <div class=\"col-auto\">\n");
      out.write("                                         <div class=\"h5 mb-0 mr-3 font-weight-bold text-gray-800\">");
      if (_jspx_meth_fmt_005fformatNumber_005f1(_jspx_page_context))
        return;
      out.write("%</div>\n");
      out.write("                                     </div>\n");
      out.write("                                     <div class=\"col\">\n");
      out.write("                                         <div class=\"progress progress-sm mr-2\">\n");
      out.write("                                             <div class=\"progress-bar bg-info\" role=\"progressbar\"\n");
      out.write("                                                 style=\"width: ");
      if (_jspx_meth_fmt_005fformatNumber_005f2(_jspx_page_context))
        return;
      out.write("%\" aria-valuenow=\"50\" aria-valuemin=\"0\"\n");
      out.write("                                                 aria-valuemax=\"100\"></div>\n");
      out.write("                                         </div>\n");
      out.write("                                     </div>\n");
      out.write("                                 </div>\n");
      out.write("                             </div>\n");
      out.write("                             <div class=\"col-auto\">\n");
      out.write("                                 <i class=\"fas fa-clipboard-list fa-2x text-gray-300\"></i>\n");
      out.write("                             </div>\n");
      out.write("                         </div>\n");
      out.write("                     </div>\n");
      out.write("                 </div>\n");
      out.write("             </div>\n");
      out.write("\n");
      out.write("             <!-- Pending Requests Card Example -->\n");
      out.write("             <div class=\"col-xl-3 col-md-6 mb-4\">\n");
      out.write("                 <div class=\"card border-left-warning shadow h-100 py-2\">\n");
      out.write("                     <div class=\"card-body\">\n");
      out.write("                         <div class=\"row no-gutters align-items-center\">\n");
      out.write("                             <div class=\"col mr-2\">\n");
      out.write("                                 <div class=\"text-xs font-weight-bold text-warning text-uppercase mb-1\">\n");
      out.write("                                     사용자 수</div>\n");
      out.write("                                 <div class=\"h5 mb-0 font-weight-bold text-gray-800\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberCnt }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("                             </div>\n");
      out.write("                             <div class=\"col-auto\">\n");
      out.write("                                 <i class=\"fas fa-comments fa-2x text-gray-300\"></i>\n");
      out.write("                             </div>\n");
      out.write("                         </div>\n");
      out.write("                     </div>\n");
      out.write("                 </div>\n");
      out.write("             </div>\n");
      out.write("         </div>\n");
      out.write("\n");
      out.write("         <!-- Content Row -->\n");
      out.write("\n");
      out.write("         <div class=\"row mb-4\">\n");
      out.write("\n");
      out.write("             <!-- Area Chart -->\n");
      out.write("             <div class=\"col-xl-6\">\n");
      out.write("                 <div class=\"card\">\n");
      out.write("                 	<div class=\"card-body\">\n");
      out.write("                 		<div id=\"columnchart_values\"  style=\"width: 100%; height: 400px;\"></div>\n");
      out.write("                 	</div>\n");
      out.write("                 </div>\n");
      out.write("             </div>\n");
      out.write("\n");
      out.write("             <!--파이 차트 -->\n");
      out.write("		    <div class=\"col-xl-6\">\n");
      out.write("		        <!-- 차트 렌더링 영역 -->\n");
      out.write("		        <div class=\"card\">\n");
      out.write("		        	<div class=\"card-body\">\n");
      out.write("		        		<div id=\"chart_div\" class=\"p-4\" style=\"width: 100%; height: 400px;\"></div>\n");
      out.write("		        	</div>\n");
      out.write("		        </div>\n");
      out.write("		    </div>\n");
      out.write("\n");
      out.write("          </div>\n");
      out.write("      <!--파이 차트 끝  -->\n");
      out.write("         <!-- Content Row -->\n");
      out.write("         <div class=\"row\">\n");
      out.write("\n");
      out.write("            <!-- Content Column -->\n");
      out.write("            <div class=\"col-lg-6 mb-4\">\n");
      out.write("\n");
      out.write("                <!-- Project Card Example -->\n");
      out.write("                <div class=\"card shadow mb-4\">\n");
      out.write("                    <div class=\"card-header py-3\">\n");
      out.write("                        <h6 class=\"m-0 font-weight-bold text-primary\">목표</h6>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"card-body\">\n");
      out.write("                        <h4 class=\"small font-weight-bold\">목표 매출: ₩");
      if (_jspx_meth_fmt_005fformatNumber_005f3(_jspx_page_context))
        return;
      out.write("원 / 현재 매출: ₩");
      if (_jspx_meth_fmt_005fformatNumber_005f4(_jspx_page_context))
        return;
      out.write("원<span\n");
      out.write("                                class=\"float-right\">");
      if (_jspx_meth_fmt_005fformatNumber_005f5(_jspx_page_context))
        return;
      out.write("%</span></h4>\n");
      out.write("                        <div class=\"progress mb-4\">\n");
      out.write("                            <div class=\"progress-bar bg-danger\" role=\"progressbar\" style=\"width: ");
      if (_jspx_meth_fmt_005fformatNumber_005f6(_jspx_page_context))
        return;
      out.write("%\"\n");
      out.write("                                aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\n");
      out.write("                        </div> \n");
      out.write("                        <h4 class=\"small font-weight-bold\">목포 사용자 수 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${targetMember }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 명 / 현재 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberCnt }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 명<span\n");
      out.write("                                class=\"float-right\">");
      if (_jspx_meth_fmt_005fformatNumber_005f7(_jspx_page_context))
        return;
      out.write("%</span></h4>\n");
      out.write("                        <div class=\"progress mb-4\">\n");
      out.write("                            <div class=\"progress-bar bg-warning\" role=\"progressbar\" style=\"width: ");
      if (_jspx_meth_fmt_005fformatNumber_005f8(_jspx_page_context))
        return;
      out.write("%\"\n");
      out.write("                                aria-valuenow=\"40\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\n");
      out.write("                        </div>\n");
      out.write("                        <h4 class=\"small font-weight-bold\">목표 주문건 :");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${targetOrder }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 건 / 현재 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ordersCnt }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 건 <span\n");
      out.write("                                class=\"float-right\">");
      if (_jspx_meth_fmt_005fformatNumber_005f9(_jspx_page_context))
        return;
      out.write("%</span></h4>\n");
      out.write("                        <div class=\"progress mb-4\">\n");
      out.write("                            <div class=\"progress-bar\" role=\"progressbar\" style=\"width: ");
      if (_jspx_meth_fmt_005fformatNumber_005f10(_jspx_page_context))
        return;
      out.write("%\"\n");
      out.write("                                aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\n");
      out.write("                        </div>  \n");
      out.write("                        <h4 class=\"small font-weight-bold\">목표 리뷰 수 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${targetReview }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 개 / 현재 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reviewCnt }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 개 <span\n");
      out.write("                                class=\"float-right\"> ");
      if (_jspx_meth_fmt_005fformatNumber_005f11(_jspx_page_context))
        return;
      out.write("%</span></h4>\n");
      out.write("                        <div class=\"progress mb-4\">\n");
      out.write("                            <div class=\"progress-bar bg-info\" role=\"progressbar\" style=\"width: ");
      if (_jspx_meth_fmt_005fformatNumber_005f12(_jspx_page_context))
        return;
      out.write("%\"\n");
      out.write("                                aria-valuenow=\"80\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\n");
      out.write("                        </div>\n");
      out.write("                        <h4 class=\"small font-weight-bold\">목표 예약 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${targetReservation }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 건 / 현재 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reservationCnt }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" <span\n");
      out.write("                                class=\"float-right\">");
      if (_jspx_meth_fmt_005fformatNumber_005f13(_jspx_page_context))
        return;
      out.write("%</span></h4>\n");
      out.write("                        <div class=\"progress\">\n");
      out.write("                            <div class=\"progress-bar bg-success\" role=\"progressbar\" style=\"width: ");
      if (_jspx_meth_fmt_005fformatNumber_005f14(_jspx_page_context))
        return;
      out.write("%\"\n");
      out.write("                                aria-valuenow=\"100\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("               \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"col-lg-6 mb-4\">\n");
      out.write("\n");
      out.write("                <!-- Illustrations -->\n");
      out.write("                <div class=\"card  mb-4\">\n");
      out.write("                    <div class=\"card-header py-3\">\n");
      out.write("                        <h6 class=\"m-0 font-weight-bold text-primary\">Schedules</h6>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"card-body\">\n");
      out.write("                       <p>1.팀 프로젝트 마슈<br><strong>1월 10일 금요일</strong><br>마슈 로고 최종회의 및 최종 디버깅</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Approach -->\n");
      out.write("                <div class=\"card shadow mb-4\">\n");
      out.write("                    <div class=\"card-header py-3\">\n");
      out.write("                        <h6 class=\"m-0 font-weight-bold text-primary\">Position</h6>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"card-body\">\n");
      out.write("                        <p>PL : 허성진 - 프로젝트 검토 및 api 개발/\n");
      out.write("\n");
      out.write("                           TA : 오정균  - 기술 가이드 및 디버깅/\n");
      out.write("\n");
      out.write("                           AA : 김은영 - 인터페이스 수정 및 디버깅/\n");
      out.write("\n");
      out.write("                           DA : 김영신 - 데이터 설계 및 디버깅/\n");
      out.write("\n");
      out.write("                           UA : 백현명 - html구조화 및 퍼블리싱 담당\n");
      out.write("                       </p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("     </div>\n");
      out.write("     <!-- /.container-fluid -->\n");
      out.write("\n");
      out.write("     <!-- Footer -->\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/admin/layout/footer.jsp", out, false);
      out.write("\n");
      out.write("     <!-- End of Footer -->\n");
      out.write("\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/admin/layout/prescript.jsp", out, false);
      out.write("\n");
      out.write("   \n");
      out.write("   <script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        // Google Charts 라이브러리 로드 및 초기화\n");
      out.write("        google.charts.load('current', { packages: ['corechart'] });\n");
      out.write("\n");
      out.write("        // 라이브러리 로드 후 drawChart 실행\n");
      out.write("        google.charts.setOnLoadCallback(drawChart);\n");
      out.write("\n");
      out.write("        async function drawChart() {\n");
      out.write("            try {\n");
      out.write("                // 데이터 요청 (서버에서 데이터를 가져옴)\n");
      out.write("                let response = await fetch(`/hurdles/admin/main.do`, { method: \"POST\" });\n");
      out.write("\n");
      out.write("                if (!response.ok) throw new Error(\"Failed to fetch data\");\n");
      out.write("\n");
      out.write("                let data = await response.json();\n");
      out.write("                console.log(data);\n");
      out.write("\n");
      out.write("                if (data != null && data.item) {\n");
      out.write("                    let items = data.item;\n");
      out.write("\n");
      out.write("                    // Google DataTable 생성\n");
      out.write("                    let googleData = new google.visualization.DataTable();\n");
      out.write("                    googleData.addColumn('string', '지역 이름'); // 지역 이름 컬럼\n");
      out.write("                    googleData.addColumn('number', '식당 수');  // 식당 수 컬럼\n");
      out.write("\n");
      out.write("                    // 데이터를 차트 데이터로 추가\n");
      out.write("                    items.forEach((item) => {\n");
      out.write("                        googleData.addRow([item.localName, item.cnt]);\n");
      out.write("                    });\n");
      out.write("\n");
      out.write("                    // 차트 옵션 설정\n");
      out.write("                    let options = {\n");
      out.write("                        title: '지역별 식당 수',\n");
      out.write("                        width: 700,\n");
      out.write("                        height: 360,\n");
      out.write("                        pieHole: 0.4, // 도넛 차트 (값이 없으면 기본 원형 차트)\n");
      out.write("                        colors: ['#4CAF50', '#FFC107', '#2196F3', '#FF5722'], // 색상 커스터마이징\n");
      out.write("                        chartArea: { width: '100%', height: '80%' }, // 차트 크기 조정\n");
      out.write("                        legend: { position: 'side' } // 범례 위치\n");
      out.write("                    };\n");
      out.write("\n");
      out.write("                    // 차트를 그릴 컨테이너 선택\n");
      out.write("                    let chart = new google.visualization.PieChart(document.getElementById('chart_div'));\n");
      out.write("                    \n");
      out.write("                    // 차트 그리기\n");
      out.write("                    chart.draw(googleData, options);\n");
      out.write("                } else {\n");
      out.write("                    console.error(\"No data found!\");\n");
      out.write("                }\n");
      out.write("            } catch (error) {\n");
      out.write("                console.error(\"Error fetching data:\", error);\n");
      out.write("                document.getElementById('chart_div').innerHTML = \"<p>데이터를 불러오지 못했습니다.</p>\";\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        google.charts.load('current', { packages: ['corechart'] });\n");
      out.write("        google.charts.setOnLoadCallback(drawChar);\n");
      out.write("                async function drawChar() {\n");
      out.write("                    try {\n");
      out.write("                        // 데이터 요청\n");
      out.write("                        let response = await fetch(`/hurdles/admin/main.do`, { method: \"POST\" });\n");
      out.write("\n");
      out.write("                        if (!response.ok) throw new Error(\"Failed to fetch data\");\n");
      out.write("\n");
      out.write("                        let data = await response.json();\n");
      out.write("                        console.log(data);\n");
      out.write("\n");
      out.write("                        if (data != null && data.price) {\n");
      out.write("                            let items = data.price;\n");
      out.write("\n");
      out.write("                            // Google DataTable 생성\n");
      out.write("                            let googleData = new google.visualization.DataTable();\n");
      out.write("                            googleData.addColumn('string', '날짜'); // 날짜 컬럼\n");
      out.write("                            googleData.addColumn('number', '매출'); // 매출 컬럼\n");
      out.write("\n");
      out.write("                            // 데이터를 DataTable에 추가\n");
      out.write("                            items.forEach((item) => {\n");
      out.write("                                googleData.addRow([item.createDate, item.payTotalPrice]);\n");
      out.write("                            });\n");
      out.write("\n");
      out.write("                            // 차트 옵션 설정\n");
      out.write("                            let options = {\n");
      out.write("                                title: '날짜별 매출',\n");
      out.write("                                width: 800,\n");
      out.write("                                height: 360,\n");
      out.write("                                bar: { groupWidth: \"75%\" }, // 막대 너비 설정\n");
      out.write("                                legend: { position: \"none\" }, // 범례 제거\n");
      out.write("                                chartArea: { width: '70%', height: '70%' }, // 차트 영역 크기\n");
      out.write("                                hAxis: { title: '날짜' }, // x축 제목\n");
      out.write("                                vAxis: { title: '매출' }, // y축 제목\n");
      out.write("                                colors: ['#4285F4'] // 막대 색상\n");
      out.write("                            };\n");
      out.write("\n");
      out.write("                            // 차트 렌더링\n");
      out.write("                            let chart = new google.visualization.ColumnChart(document.getElementById('columnchart_values'));\n");
      out.write("                            chart.draw(googleData, options);\n");
      out.write("                        } else {\n");
      out.write("                            console.error(\"No data found!\");\n");
      out.write("                            document.getElementById('columnchart_values').innerHTML = \"<p>데이터가 없습니다.</p>\";\n");
      out.write("                        }\n");
      out.write("                    } catch (error) {\n");
      out.write("                        console.error(\"Error fetching data:\", error);\n");
      out.write("                        document.getElementById('columnchart_values').innerHTML = \"<p>데이터를 불러오지 못했습니다.</p>\";\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            </script>\n");
      out.write("	</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/view/admin/main.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("nav");
    // /WEB-INF/view/admin/main.jsp(6,0) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/admin/main.jsp(6,0) 'main'",_jsp_getExpressionFactory().createValueExpression("main",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/view/admin/main.jsp(6,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setScope("request");
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatNumber_005f0.setParent(null);
    // /WEB-INF/view/admin/main.jsp(55,87) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${payTotalPrice }", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/view/admin/main.jsp(55,87) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f0.setPattern("#,###");
    int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
    if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    _jspx_th_fmt_005fformatNumber_005f1.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatNumber_005f1.setParent(null);
    // /WEB-INF/view/admin/main.jsp(75,98) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ordersPerReview }", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/view/admin/main.jsp(75,98) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f1.setPattern("#.#");
    int _jspx_eval_fmt_005fformatNumber_005f1 = _jspx_th_fmt_005fformatNumber_005f1.doStartTag();
    if (_jspx_th_fmt_005fformatNumber_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f1);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f2 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    _jspx_th_fmt_005fformatNumber_005f2.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatNumber_005f2.setParent(null);
    // /WEB-INF/view/admin/main.jsp(80,63) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ordersPerReview }", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/view/admin/main.jsp(80,63) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f2.setPattern("#.#");
    int _jspx_eval_fmt_005fformatNumber_005f2 = _jspx_th_fmt_005fformatNumber_005f2.doStartTag();
    if (_jspx_th_fmt_005fformatNumber_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f2);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f3(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f3 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    _jspx_th_fmt_005fformatNumber_005f3.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatNumber_005f3.setParent(null);
    // /WEB-INF/view/admin/main.jsp(150,67) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${targetPrice }", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/view/admin/main.jsp(150,67) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f3.setPattern("#,###");
    int _jspx_eval_fmt_005fformatNumber_005f3 = _jspx_th_fmt_005fformatNumber_005f3.doStartTag();
    if (_jspx_th_fmt_005fformatNumber_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f3);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f4(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f4 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    _jspx_th_fmt_005fformatNumber_005f4.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatNumber_005f4.setParent(null);
    // /WEB-INF/view/admin/main.jsp(150,138) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${payTotalPrice }", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/view/admin/main.jsp(150,138) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f4.setPattern("#,###");
    int _jspx_eval_fmt_005fformatNumber_005f4 = _jspx_th_fmt_005fformatNumber_005f4.doStartTag();
    if (_jspx_th_fmt_005fformatNumber_005f4.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f4);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f5(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f5 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    _jspx_th_fmt_005fformatNumber_005f5.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatNumber_005f5.setParent(null);
    // /WEB-INF/view/admin/main.jsp(151,52) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f5.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${targetPP }", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/view/admin/main.jsp(151,52) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f5.setPattern("#.#");
    int _jspx_eval_fmt_005fformatNumber_005f5 = _jspx_th_fmt_005fformatNumber_005f5.doStartTag();
    if (_jspx_th_fmt_005fformatNumber_005f5.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f5);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f6(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f6 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    _jspx_th_fmt_005fformatNumber_005f6.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatNumber_005f6.setParent(null);
    // /WEB-INF/view/admin/main.jsp(153,97) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f6.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${targetPP }", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/view/admin/main.jsp(153,97) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f6.setPattern("#.#");
    int _jspx_eval_fmt_005fformatNumber_005f6 = _jspx_th_fmt_005fformatNumber_005f6.doStartTag();
    if (_jspx_th_fmt_005fformatNumber_005f6.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f6);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f7(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f7 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    _jspx_th_fmt_005fformatNumber_005f7.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatNumber_005f7.setParent(null);
    // /WEB-INF/view/admin/main.jsp(157,52) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f7.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${targetMM }", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/view/admin/main.jsp(157,52) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f7.setPattern("#.#");
    int _jspx_eval_fmt_005fformatNumber_005f7 = _jspx_th_fmt_005fformatNumber_005f7.doStartTag();
    if (_jspx_th_fmt_005fformatNumber_005f7.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f7);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f8(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f8 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    _jspx_th_fmt_005fformatNumber_005f8.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatNumber_005f8.setParent(null);
    // /WEB-INF/view/admin/main.jsp(159,98) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f8.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${targetMM }", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/view/admin/main.jsp(159,98) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f8.setPattern("#.#");
    int _jspx_eval_fmt_005fformatNumber_005f8 = _jspx_th_fmt_005fformatNumber_005f8.doStartTag();
    if (_jspx_th_fmt_005fformatNumber_005f8.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f8);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f9(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f9 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    _jspx_th_fmt_005fformatNumber_005f9.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatNumber_005f9.setParent(null);
    // /WEB-INF/view/admin/main.jsp(163,52) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f9.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${targetOO }", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/view/admin/main.jsp(163,52) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f9.setPattern("#.#");
    int _jspx_eval_fmt_005fformatNumber_005f9 = _jspx_th_fmt_005fformatNumber_005f9.doStartTag();
    if (_jspx_th_fmt_005fformatNumber_005f9.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f9);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f10(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f10 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    _jspx_th_fmt_005fformatNumber_005f10.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatNumber_005f10.setParent(null);
    // /WEB-INF/view/admin/main.jsp(165,87) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f10.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${targetOO }", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/view/admin/main.jsp(165,87) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f10.setPattern("#.#");
    int _jspx_eval_fmt_005fformatNumber_005f10 = _jspx_th_fmt_005fformatNumber_005f10.doStartTag();
    if (_jspx_th_fmt_005fformatNumber_005f10.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f10);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f11(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f11 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    _jspx_th_fmt_005fformatNumber_005f11.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatNumber_005f11.setParent(null);
    // /WEB-INF/view/admin/main.jsp(169,53) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f11.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${targetRR }", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/view/admin/main.jsp(169,53) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f11.setPattern("#.#");
    int _jspx_eval_fmt_005fformatNumber_005f11 = _jspx_th_fmt_005fformatNumber_005f11.doStartTag();
    if (_jspx_th_fmt_005fformatNumber_005f11.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f11);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f12(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f12 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    _jspx_th_fmt_005fformatNumber_005f12.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatNumber_005f12.setParent(null);
    // /WEB-INF/view/admin/main.jsp(171,95) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f12.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${targetRR }", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/view/admin/main.jsp(171,95) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f12.setPattern("#.#");
    int _jspx_eval_fmt_005fformatNumber_005f12 = _jspx_th_fmt_005fformatNumber_005f12.doStartTag();
    if (_jspx_th_fmt_005fformatNumber_005f12.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f12);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f13(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f13 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    _jspx_th_fmt_005fformatNumber_005f13.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatNumber_005f13.setParent(null);
    // /WEB-INF/view/admin/main.jsp(175,52) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f13.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${targetRes }", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/view/admin/main.jsp(175,52) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f13.setPattern("#.#");
    int _jspx_eval_fmt_005fformatNumber_005f13 = _jspx_th_fmt_005fformatNumber_005f13.doStartTag();
    if (_jspx_th_fmt_005fformatNumber_005f13.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f13);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f14(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f14 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    _jspx_th_fmt_005fformatNumber_005f14.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatNumber_005f14.setParent(null);
    // /WEB-INF/view/admin/main.jsp(177,98) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f14.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${targetRes }", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/view/admin/main.jsp(177,98) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f14.setPattern("#.#");
    int _jspx_eval_fmt_005fformatNumber_005f14 = _jspx_th_fmt_005fformatNumber_005f14.doStartTag();
    if (_jspx_th_fmt_005fformatNumber_005f14.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f14);
    return false;
  }
}
